# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17RCvOXGiUOvUiSdzdJufl4IJknCWxDxe
"""

from PIL import Image, ImageDraw, ImageFont
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

   
def coupons(name: list,team_name:list, certificate: str, font_path: str):
    i=-1
    for name in name:
        i=i+1
        # adjust the position according to 
        # your sample
        text_y_position = 900 
   
        # opens the image
        img = Image.open('template.png', mode ='r')
      
        # gets the image width
        image_width = img.width
        
        # gets the image height
        image_height = img.height
        print(image_height)
        print(image_width) 
   
        # creates a drawing canvas overlay 
        # on top of the image
        draw = ImageDraw.Draw(img)
   
        # gets the font object from the 
        # font file (TTF)
        font = ImageFont.truetype(
            'Montserrat-Regular.ttf',
            45 # change this according to your needs
        )
   
        # fetches the text width for 
        # calculations later on
        text_width, _ = draw.textsize(name, font = font)

        draw.text(
            (
                # this calculation is done 
                # to centre the image
                (image_width - text_width) / 4-200,
                text_y_position+60
            ),
            name,
            font = font)
        draw.text(
            (
                # this calculation is done 
                # to centre the image
                
                3*(image_width - text_width) / 4-250,
                text_y_position+60
            ),
            team_name[i],
            font = font)
        draw.text(
            (
                # this calculation is done 
                # to centre the image
                600,
                text_y_position+165
            ),
            '3rd',
            font = font)
        # saves the image in png format
        img.save("/content/drive/MyDrive/folder-name/{}.png".format(name)) 
  
# Driver Code
if __name__ == "__main__":
   
    name=[]
    team_name=[]
    print("Initializing Script!")
    names = pd.read_csv('participants.csv')
    for i,row in names.iterrows():
        name.append( str(row['Name']))
        team_name.append(str(row['Team']))

      
    # path to font
    FONT = "/path / to / font / ITCEDSCR.ttf"
      
    # path to sample certificate
    CERTIFICATE = "path / to / Certificate.png"
   
    coupons(name,team_name, CERTIFICATE, FONT)

"""# New Section"""